package com.example.ui

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val appTitle: String,
    val shop: String,
    val cart: String,
    val admin: String,
    val logout: String,
    val emailOrPhone: String,
    val password: String,
    val loginAsAdmin: String,
    val loginBtn: String,
    val loginHint: String,
    val all: String,
    val feed: String,
    val medicine: String,
    val appetite: String,
    val addBtn: String,
    val outOfStock: String,
    val cartEmpty: String,
    val yourCart: String,
    val total: String,
    val payViaUpi: String,
    val inventoryMgmt: String,
    val addProduct: String,
    val name: String,
    val categoryHint: String,
    val desc: String,
    val price: String,
    val stock: String,
    val cancel: String,
    val languageToggle: String,
    val errorEmptyFields: String,
    val errorInvalidAdmin: String,
    val errorInvalidInput: String
)

val englishStrings = AppStrings(
    appTitle = "Shahnawaz Pasu Ahaar",
    shop = "Shop",
    cart = "Cart",
    admin = "Admin",
    logout = "Logout",
    emailOrPhone = "Email or Phone",
    password = "Password",
    loginAsAdmin = "Login as Admin (Owner)",
    loginBtn = "Login",
    loginHint = "Hint: admin / admin123",
    all = "All",
    feed = "Feed",
    medicine = "Medicine",
    appetite = "Appetite",
    addBtn = "Add",
    outOfStock = "Out of Stock",
    cartEmpty = "Your cart is empty.",
    yourCart = "Your Cart",
    total = "Total:",
    payViaUpi = "Pay via UPI",
    inventoryMgmt = "Inventory Management",
    addProduct = "Add Product",
    name = "Name",
    categoryHint = "Category",
    desc = "Description",
    price = "Price",
    stock = "Stock",
    cancel = "Cancel",
    languageToggle = "A/अ",
    errorEmptyFields = "Please enter email and password",
    errorInvalidAdmin = "Invalid admin credentials",
    errorInvalidInput = "Please enter valid details"
)

val hindiStrings = AppStrings(
    appTitle = "शाहनवाज़ पशु आहार",
    shop = "दुकान",
    cart = "कार्ट",
    admin = "प्रबंधक",
    logout = "लॉग आउट",
    emailOrPhone = "ईमेल या फोन",
    password = "पासवर्ड",
    loginAsAdmin = "एडमिन के रूप में लॉगिन करें",
    loginBtn = "लॉगिन",
    loginHint = "संकेत: admin / admin123",
    all = "सभी",
    feed = "चारा",
    medicine = "दवा",
    appetite = "भूख",
    addBtn = "जोड़ें",
    outOfStock = "स्टॉक समाप्त",
    cartEmpty = "आपका कार्ट खाली है।",
    yourCart = "आपका कार्ट",
    total = "कुल:",
    payViaUpi = "UPI से भुगतान",
    inventoryMgmt = "इन्वेंटरी प्रबंधन",
    addProduct = "उत्पाद जोड़ें",
    name = "नाम",
    categoryHint = "श्रेणी",
    desc = "विवरण",
    price = "मूल्य",
    stock = "स्टॉक",
    cancel = "रद्द करें",
    languageToggle = "A/अ",
    errorEmptyFields = "कृपया ईमेल और पासवर्ड दर्ज करें",
    errorInvalidAdmin = "अमान्य एडमिन क्रेडेंशियल",
    errorInvalidInput = "कृपया मान्य विवरण दर्ज करें"
)

val LocalAppStrings = staticCompositionLocalOf { englishStrings }
